image:
  repository: ghcr.io/clbs-io/cloudflare-tunnel-ingress-controller
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingressClass:
  name: cloudflare-tunnel
  controller: github.com/clbs-io/cloudflare-tunnel-ingress
  isDefaultClass: false

config:
  cloudflared:
    image: cloudflare/cloudflared:2024.9.1
    imagePullPolicy: IfNotPresent

  cloudflare:
    accountID: xxx
    tunnelName: xxx

    apiToken:
      existingSecret:
        name: cloudflare-api-token
        key: token

  kubernetesApiTunnel:
    enabled: false
    server: kubernetes.default.svc:443
    domain: domain.example.com
    cloudflareAccessAppName: "Kubernetes API Tunnel"
