image:
  repository: ghcr.io/cybroslabs/cloudflare-tunnel-ingress-controller
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingressClass:
  name: cloudflare-tunnel
  controller: github.com/cybroslabs/cloudflare-tunnel-ingress
  isDefaultClass: false

config:
  cloudflared:
    image: cloudflare/cloudflared:2024.5.0
    imagePullPolicy: IfNotPresent

  cloudflare:
    accountID: xxx
    tunnelName: xxx

    apiToken:
      existingSecret:
        name: cloudflare-api-token
        key: token
