nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: registry.clbs.io/clbs-io/cloudflare-tunnel-ingress-controller/main
  tag:
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingressClass:
  name: cloudflare-tunnel
  controller: clbs.io/cloudflare-tunnel-ingress-controller
  isDefaultClass: false

config:
  cloudflared:
    image: cloudflare/cloudflared:2026.2.0
    imagePullPolicy: IfNotPresent

  cloudflare:
    accountID: ""
    tunnelName: ""

    apiToken:
      existingSecret:
        name: cloudflare-api-token
        key: token

  kubernetesApiTunnel:
    enabled: false
    server: kubernetes.default.svc:443
    domain: domain.example.com
    cloudflareAccessAppName: "Kubernetes API Tunnel"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

nodeSelector: {}
tolerations: []
affinity: {}
