
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-watch-ingresses
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-watch-ingresses
subjects:
  - name: {{ .Release.Name }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
