apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudflare-tunnel-ingress-controller.fullname" . }}-cloudflared
  labels:
    {{- include "cloudflare-tunnel-ingress-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudflare-tunnel-ingress-controller.fullname" . }}-cloudflared
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-tunnel-ingress-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
