apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflare-tunnel-ingress-controller.serviceAccountName" . }}
  labels:
    {{- include "cloudflare-tunnel-ingress-controller.labels" . | nindent 4 }}
